#!/usr/bin/env ruby
#^syntax detection

forge 'https://forgeapi.puppetlabs.com'

mod 'puppetlabs-stdlib'

mod 'puppetfinland-apache2',
    :git => 'https://github.com/Puppet-Finland/apache2.git'

mod 'puppetfinland-gettext',
    :git => 'https://github.com/Puppet-Finland/gettext.git'

mod 'puppetfinland-localbackups',
    :git => 'https://github.com/Puppet-Finland/localbackups.git'

mod 'puppetfinland-locales',
    :git => 'https://github.com/Puppet-Finland/locales.git'

mod 'puppetfinland-monit',
    :git => 'https://github.com/Puppet-Finland/monit.git'

mod 'puppetfinland-os',
    :git => 'https://github.com/Puppet-Finland/os.git'

mod 'puppetfinland-packetfilter',
    :git => 'https://github.com/Puppet-Finland/packetfilter.git'

mod 'puppetfinland-pf_postgresql',
    :git => 'https://github.com/Puppet-Finland/postgresql.git'

mod 'puppetfinland-python',
    :git => 'https://github.com/Puppet-Finland/python.git'

mod 'puppetfinland-subversion',
    :git => 'https://github.com/Puppet-Finland/subversion.git'

mod 'puppetfinland-systemd',
    :git => 'https://github.com/Puppet-Finland/systemd.git'

mod 'puppetfinland-webserver',
    :git => 'https://github.com/Puppet-Finland/webserver.git'

